tinyMCE.addToLang('',{
	bold_desc:'Bold',
	separator_desc:'Separator',
	strikethrough_desc:'Strikethrough',
	left_desc:'Justify left',
	center_desc:'Justify center',
	right_desc:'Justify right',
	full_desc:'Justify full',
	sub_desc:'Subscript',
	sup_desc:'Superscript',
	forecolor_desc:'Select text color',
	backcolor_desc:'Select background color',
	removeformat_desc:'Remove formatting',
	anchor_desc:'Insert/edit anchor',
	hr_desc:'Horizontal line (simple)',
	charmap_desc:'Insert custom character',
	code_desc:'Edit HTML source',
	tablecontrols_desc:'Inserts a new table',
	zoom_desc:'Zoom (only IE)',
	fontselect_desc:'Select font',
	fontsizeselect_desc:'Select fontsize',
	formatselect_desc:'Paragraph',
	styleselect_desc:'CSS styles',
	visualaid_desc:'Toggle guidelines/invisible elements',
	xrmanager_desc:'Filebrowser',
	advhr_desc:'Horizontal line (advanced)',
	advimage_desc:'Insert/edit image (advanced)',
	advlink_desc:'Insert/edit link (advanced)',
	emotions_desc:'Emotions',
	flash_desc:'Insert Flash movie',
	insertdate_desc:'Insert date',
	inserttime_desc:'Insert time',
	preview_desc:'Preview',
	print_desc:'Print',
	search_desc:'Find',
	replace_desc:'Find/replace',
	iespell_desc:'Spellcheck (only IE)',
	xquote_desc:'XOOPS-Quote',
	blockproperties_desc:'Block properties',
	xcode_desc:'XOOPS-Code',
	mlcontent_desc:'Insert multilanguage content',
	pasteword_desc:'Paste from Word',
	pastetext_desc:'Paste as plain text',
	selectall_desc:'Select all',
	ltr_desc:'Direction left to right',
	rtl_desc:'Direction right to left',
	fullscreen_desc:'Toggle fullscreen mode',
	imanager_desc:'iManager',
	ibrowser_desc:'iBrowser',
	charcount_desc:'Word/character count',
	insertcode_desc:'Insert some code (with syntax-highlighting)',
	insertdiv_desc:'Visual DIV editor',
	custombullet_desc:'This creates definition lists',
	noneditable_desc:'Protect elements from editing',
	ximagemanager_desc:'XOOPS-Imagemanager',
	contextmenu_desc:'Contextmenu',
	keyboard_desc:'Unicode Keyboard',
	pagebreak_desc:'Inserts pagebreak',
	equation_desc:'Equation',
	spellchecker_desc:'Spellchecker (Crossbrowser)',
	youtube_desc:'Inserts YouTube movies',
	media_desc:'Insert / edit embedded media',
	nonbreaking_desc:'Insert non-breaking space character',
	cite_desc:'Citation',
	abbr_desc:'Abbreviation',
	acronym_desc:'Acronym',
	ins_desc:'Insertion',
	del_desc:'Deletion',
	visualchars:'Visual control-characters on/off',
	htmltemplate_desc:'Open templates',
	savehtmltemplate_desc:'Save templates',
	style_desc:'Advanced text formatting',
	layer_desc:'Inserts simple layers',
	devkit_desc:'Debugger for the tiny-plugins',
	visualchars_desc:'Visual control characters on/off'});