<?php
/*
* $Id: xoops_version.php
* Module: XMAIL
* Version: v2.5
* Release Date: 18 Março 2005
* Author: Claudia Antonini Vitiello Callegari and Gilberto G. de Oliveira (GibaPhp)
* License: GNU
*/

// version  2.5 alpha
$modversion['name']            = _MI_XMAIL_NAME;
$modversion['version']         = 2.52;
$modversion['description']     = _MI_XMAIL_DESC;
$modversion['author']          = "Claudia";
$modversion['co-author']       = "GibaPhp";
$modversion['credits']         = "http://www.xoopstotal.com.br";
$modversion['help']            = "xmail-help.html";
$modversion['image']           = "images/logo-xmail.png";
$modversion['license']         = "<a href='http://creativecommons.org/licenses/GPL/2.0/' target='_blank'>Human-Readable Commons Deed</a> - <a href='http://www.gnu.org/copyleft/gpl.html' target='_blank'>Full Legal Code</a>";
$modversion['official']        = 0;                          // Se este módulo é ofical (1)um ou (0) não.
$modversion['dirname']         = "xmail";
//_MI_XMAIL_DIRNAME;          // Alterar aqui este nome mantendo o padrão.

// Opcionais e sugestões de padronização para adoção.
$modversion['author_realname'] = "Claudia A. V. Callegari";  // Real name author
$modversion['site-author']     = _MI_XMAIL_SITE_AUTHOR ;     // URL do site do autor. Nem sempre será o mesmo do local de desenvolvimento.
$modversion['dev-site']        = _MI_XMAIL_DEV_SITE;         // Endereço do site de desenvolvimento.
$modversion['support']         = _MI_XMAIL_SUPPORT;          // URL site de suporte ou fórum de suporte. - No futuro web-service para agendar suporte.
$modversion['report-bugs']     = _MI_XMAIL_REPORT_BUGS;      // URL de site ou fórum para reportar bugs.
$modversion['report-features'] = _MI_XMAIL_REPORT_FEATURES;  // URL de site ou fórum para enviar sugestões de melhorias.
$modversion['new-version']     = _MI_XMAIL_NEW_VERSION;      // URL de site ou download para nova versão.
$modversion['qas-check-in']    = _MI_XMAIL_QAS_CHECK_PASSED; // URL de Página para os testes realizados com esta versão.
$modversion['dependences']     = _MI_XMAIL_DEPENDENCES;      // Quais as dependencias que este módulo possui, exemplo, FrameWork, SmartObjects, XtDevObjects, etc..
$modversion['compatible']      = _MI_XMAIL_COMPATIBLE;       // Quais as versões que este módulo é compátivel.

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/xmail.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "xmail_mensage";
$modversion['tables'][1] = "xmail_send_log";
$modversion['tables'][2] = "xmail_param";
$modversion['tables'][3] = "xmail_files";
$modversion['tables'][4] = "xmail_men_anexo";
$modversion['tables'][5] = "xmail_ativacao";
$modversion['tables'][6] = "xmail_aux_send";
$modversion['tables'][7] = "xmail_aux_send_l";
$modversion['tables'][8] = "xmail_newsletter";
$modversion['tables'][9] = "xmail_perfil_news";
$modversion['tables'][10] = "xmail_tabperfil";


// Search
$modversion['hasSearch'] = 0;
$modversion['search']['file'] = "";
$modversion['search']['func'] = "";

// Menu
$modversion['hasMain'] = 1;
$modversion['sub'][1]['name'] = _MI_XMAIL_SMNAME1;
$modversion['sub'][1]['url'] = "submit.php?op=add";
$modversion['sub'][2]['name'] = _MI_XMAIL_SMNAME2;
$modversion['sub'][2]['url'] = "gerencia.php";
$modversion['sub'][3]['name'] = _MI_XMAIL_ADMENU3;
$modversion['sub'][3]['url'] = "verlog.php";


// Templates      alterar os nomes  p/  xmail
$modversion['templates'][1]['file'] = 'xmail_mensage.htm';
$modversion['templates'][1]['description'] = 'Mostra mensagens ';
$modversion['templates'][2]['file'] = 'xmail_verlog.htm';
$modversion['templates'][2]['description'] = 'Mostra log de envio de mensagens';
$modversion['templates'][3]['file'] = 'xmail_lote.htm';
$modversion['templates'][3]['description'] = 'Mostra log de envio de mensagens';
$modversion['templates'][4]['file'] = 'xmail_unsub.html';
$modversion['templates'][4]['description'] = 'Cancelar assinatura newsletter';
$modversion['templates'][5]['file'] = 'xmail_subscr.html';
$modversion['templates'][5]['description'] = 'Assinar newsletter';

$modversion['templates'][6]['file'] = 'xmail_notice.html';
$modversion['templates'][6]['description'] = 'newsletter ';

$modversion['templates'][7]['file'] = 'xmail_index.html';
$modversion['templates'][7]['description'] = 'newsletter ';


// Comments
$modversion['hasComments'] = 0;

// blocks
$modversion['blocks'][1]['file'] = "block_xmail.php";
$modversion['blocks'][1]['name'] = _MI_XMAIL_BLOCK1 ;
$modversion['blocks'][1]['description'] = _MI_XMAIL_DESCRIBLOCK1 ;
$modversion['blocks'][1]['show_func'] = "b_xmail_show_ativa";
$modversion['blocks'][1]['edit_func'] = "b_xmail_edit_ativa";

$modversion['blocks'][2]['file'] = "block_xmail.php";
$modversion['blocks'][2]['name'] = _MI_XMAIL_BLOCK2 ;
$modversion['blocks'][2]['description'] = _MI_XMAIL_DESCRIBLOCK2 ;
$modversion['blocks'][2]['show_func'] = "b_xmail_show_news";
$modversion['blocks'][2]['edit_func'] = "b_xmail_edit_news";
$modversion['blocks'][2]['template'] = 'xmail_block_subcr.html';


$modversion['blocks'][3]['file'] = "block_xmail.php";
$modversion['blocks'][3]['name'] = _MI_XMAIL_BLOCK3 ;
$modversion['blocks'][3]['description'] = _MI_XMAIL_DESCRIBLOCK3 ;
$modversion['blocks'][3]['show_func'] = "b_xmail_ulti_news";
$modversion['blocks'][3]['edit_func'] = "b_xmail_edit_ulti_news";
//$modversion['blocks'][3]['template'] = 'xmail_block_subcr.html';

// não usar bloco,  usar o send_agenda_ajax.php

//$modversion['blocks'][4]['file'] = "block_xmail.php";
//$modversion['blocks'][4]['name'] = _MI_XMAIL_BLOCK4 ;
//$modversion['blocks'][4]['description'] = _MI_XMAIL_DESCRIBLOCK4 ;
//$modversion['blocks'][4]['show_func'] = "b_xmail_send_agenda_ajax";
//$modversion['blocks'][4]['edit_func'] = "b_xmail_send_agenda_ajax_edit";


$modversion['onInstall'] = 'installscript.php';

?>
